### ISSUE TITLE
Document the way to use default and custom formatters

### ISSUE THREAD

**Issue by arty-name** [messageformat/messageformat.js#145]
I remembered that MessageFormat supported formatting of dates and numbers, but when I tried that, I got errors like `fmt.date is not a function`. I had to dig into the code to find that even the [default formatters have to be included separately](https://messageformat.github.io/messageformat.js/doc/MessageFormat.formatters.html). 

It would be great to mention that in a more visible part of https://messageformat.github.io/

**Comment by eemeli** [comment]
You're right. I'll take a look at the documentation, and try to make this a bit more obvious. Unfortunately, node 0.10 and IE 10 are still widely enough used that defaulting to code that would fail on them is not really viable.
