### ISSUE TITLE
Consider moving this repo to messageformat/messageformat.js

### ISSUE THREAD

**Issue by eemeli** [messageformat/messageformat.js#152]
With the imminent 1.0 release, it seems like an appropriate time to consider moving this repo from `SlexAxton/messageformat.js` to `messageformat/messageformat.js`, i.e. under the @messageformat org from its current place under @SlexAxton's private space where it's been since its creation over four years ago.

I created the org originally in order to get the [messageformat.github.io](https://messageformat.github.io/) domain, and have since added the [messageformat/parser](https://github.com/messageformat/parser) repo to it, which now holds the PEG.js -based parser used by messageformat.js. The org currently has @SlexAxton and myself as owner-level members.

My main reason for asking for this is that it feels weird to contribute as much as I do to a project that's in another person's private namespace. Also, IMHO having the @messageformat namespace is kinda cool, and that we should make more use of it.

With GitHub, moving a repo will automatically add forwarding rules, so all prior links will continue to work and direct to the new repo.

So, thoughts?

**Comment by SlexAxton** [comment]
Yep. Sounds good, makes sense. Let's move it.

Somewhat relevantly, the Dojo Foundation merged with the jQuery Foundation and both of us need to sign the new jQuery Foundation CAA for the project. I'll email it to you if that's alright.
