### ISSUE TITLE
Which js file to include - bin/ or lib/?

### ISSUE THREAD

**Issue by marie-dk** [messageformat/messageformat.js#157]
I have installed messageformat from npm:
`npm install messageformat --save-dev`

But there is both a bin and a lib folder in the project. Both contain messageformat.js, but none of them are working. If I instead include messageformat from CDN, everything works as expected. None of the files in the npm project looks anything like the one from CDN.

If I include node_modules/messageformat/lib/messageformat.js I get a "module is not defined" error. If I include node_modules/messageformat/bin/messageformat.js I get "invalid or unexpected token" ... Therefore I suspect there is a step missing to get a script like the one from CDN... I just don't know what it is?

**Comment by cudasteve** [comment]
I think my question is related.  I'd like to install a "browser-ready" build that could be used directly on the frontend (run in a "script tag" if you will).

It seems to me that if I install with bower, I'll get a file at messageformat/messageformat.js that I can include in my ES5 build process just fine.  But installing with npm seems to assume I'm going to use it in node and doesn't give me that brower-ready file.

Is this intentional or am I missing something?  I'd prefer to use npm.

**Comment by daveshapiro** [comment]
I also can't figure this out.  I've tried a few of the various versions available at https://cdnjs.com/libraries/messageformat and can't get most of them to work either.

Anyone figured this out since the issue was opened?

**Comment by marie-dk** [comment]
@daveshapiro I am using rawgit, not cdnjs... sorry if I was a bit unclear about that. This one works for me: https://cdn.rawgit.com/SlexAxton/messageformat.js/v0.3.1/messageformat.js

**Comment by eemeli** [comment]
Hi, sorry for not getting to this issue until now. The source JS files included in the repo's `master` branch are not directly usable in browsers. However, the tagged [releases](../releases) do include compiled and minified UMD versions of messageformat.js that are exactly meant for use in browsers. Via rawgit.com, the latest release [1.0.0](../releases/tag/v1.0.0) is available as both [compiled](https://cdn.rawgit.com/SlexAxton/messageformat.js/v1.0.0/messageformat.js) and as additionally [minified](https://cdn.rawgit.com/SlexAxton/messageformat.js/v1.0.0/messageformat.min.js) files.

Also, with the 1.0.0 release the npm package now also includes the UMD version of the library as `messageformat/messageformat.js`; the `package.json` file maps calls for `require('messageformat')` to the source at `lib/index.js` instead.

The cdnjs.com version is not managed by us directly, and it looks like it's a broken, partial copy of the source files for at least most of our version history. Should probably get them to fix it, or take it down.

**Comment by daveshapiro** [comment]
Beauty!  Thanks!

**Comment by cudasteve** [comment]
The npm version of v1.0.0 is working with global variable access for me.  Thanks!

**Comment by marie-dk** [comment]
Works like a charm... thank you @eemeli
