### ISSUE TITLE
Cannot format numbers using Intl Polyfill

### ISSUE THREAD

**Issue by ncintra** [messageformat/messageformat.js#161]
Hi,

First of all thanks for this great library!

I'm trying to use messageformat (v.1.0.0) to format/localize messages in nodejs (v4.5.0).

For Intl to work in nodejs (other then 'en' language) I'm loading the Intl Polyfill library (v1.2.5).

I can successfully localise messages with date, time and custom formatters but I can't get it to work with the number formatter. Here's an example:

        //require Intl Polyfill
        let IntlPolyfill = require('intl');
       
        Intl.NumberFormat   = IntlPolyfill.NumberFormat;
       
        Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
  
        let MessageFormat = require('messageformat');

        let mf = new MessageFormat('es-ES').setIntlSupport(true);

        return mf.compile('{area, number, integer} SF')({ area: 3000.00 });

Here's the error I'm getting:

TypeError: Intl.NumberFormat(...).format is not a function
    at Object.eval [as number] (eval at <anonymous> 

(\node_modules\messageformat\lib\index.js:125:12), <anonymous>:7:9)
    at eval (eval at <anonymous> (\node_modules\messageformat\lib\index.js:458:14), <anonymous>:3:33)

I only get this error when I'm using the Intl polyfill. Without it I don't get the error but I can't localise for the different locales.

Thanks in advance!

**Comment by eemeli** [comment]
Thank you for the bug report! This is now fixed in [`1.0.2`](../releases/tag/v1.0.2).
