### ISSUE TITLE
Can't use npm package in browser

### ISSUE THREAD

**Issue by laurentperroteau** [messageformat/messageformat.js#163]
Hi,

In the browser, I can't use JS file when I install with NPM package (`module is undefined` error), but it works with Bower !

Is it possible to adapt the packaging for use in the browser?

Thanks

**Comment by eemeli** [comment]
Could you give a more specific example of exactly how you're including messageformat.js, and at what point you're getting that error? The npm-published version should already include a version that's suitable for in-browser use, at `messageformat.js/messageformat.js` and `messageformat.js/messageformat.min.js`.

**Comment by laurentperroteau** [comment]
Sorry, I use the package **angular-translate-interpolation-messageformat** and it's still using **messageformat** version 0.3.1.

I create an [issue](https://github.com/angular-translate/angular-translate/issues/1644) on it.
