### ISSUE TITLE
How to use build-time compiler with intl support

### ISSUE THREAD

**Issue by hey99xx** [messageformat/messageformat.js#167]
Currently I do not see any way to use the build-time compilation ( https://messageformat.github.io/build/ )  and support "date" function at the same type.
The 'bin/messageformat' executable does not take intl as an argument, that could set `setIntlSupport(true)`. Should that be an option?

**Comment by hey99xx** [comment]
And to be clear, my question is not specific to "date" type but all intl formatters in https://messageformat.github.io/guide/#intl-formatters

**Comment by hey99xx** [comment]
I have locally made the following change

    if (options['disable-plural-key-checks']) mf.disablePluralKeyChecks();
    if (options['enable-intl-support']) mf.setIntlSupport(true); // NEW LINE
    var output = mf.compile(input).toString(ns);

Afterwards I use the compiler cli with `./node_modules/.bin/messageformat -enable-intl-support` which works fine.

**Comment by eemeli** [comment]
You're right, `--enable-intl-support` should be added to the CLI. In addition to your one-line change, we should add a shorthand `-i` and a mention in the documentation.

@hey99xx, if you could submit a PR for this, I'd be happy to accept it?

**Comment by hey99xx** [comment]
Sure, I will try to add it tomorrow during work day for me.

**Comment by SlexAxton** [comment]
Fixed by #168
