### ISSUE TITLE
PluralFormat: one vs =1 inconsistency

### ISSUE THREAD

**Issue by wkeese** [messageformat/messageformat.js#170]
The examples on https://messageformat.github.io/ show PluralFormat using `one` rather than `=1`, but that produces an error in the console, at least on firefox:

> Error: Invalid key `one` for argument `count`. Valid plural keys for this locale are `other`, and explicit keys like `=0`.

So either the code or the doc should be updated... I guess the doc.

**Comment by SlexAxton** [comment]
That is a valid key for english, but not for japanese, for instance. What is the exact code you're running?

**Comment by wkeese** [comment]
Oh, I didn't think about that.  Actually I do have Firefox set to Japanese, and consequently am initializing MessageFormat to ja, via `new MessageFormat(navigator.language.replace(/-.*$/, ""))` so I guess this isn't a bug.

The reason my string had `one` in it was because the text has actually been translated to Japanese yet, and is still in English.
