### ISSUE TITLE
alias to "zero, two, few[, many]"

### ISSUE THREAD

**Issue by Spown** [messageformat/messageformat.js#172]
these keys 
-  zero
- two
- few
- many

were valid in ver ``^0`` but not anymore as it seems. Why not alias them to ``=0``, ``=2``, ``=3`` instead of throwing an exception? I guess you could ditch ``many``. But I mean its not like it leads to ambiguity if it's already leads to only option of an exception. Also you still have 
```
'{CAT, selectordinal, one{#st} two{#nd} few{#rd} other{#th} }'
```
in your Readme

Personally I don't really care - I've never used this module. I'm just trying to up the deps of my ``i18n-node`` module fork (I haven't really found any use for it's ``_mf`` method that employs this module). It's just that by upping ``messageformat.js`` to ``^1`` tests start to fail. I can fix it but I don't see why this change was even necessary.

**Comment by SlexAxton** [comment]
These keywords should still be valid. It sounds like something else is up. Literals (like `=3`) are not a 1:1 replacement for keywords (like `few`). As far as I know these work well (and are all over the test suite).

**Comment by Spown** [comment]
Using ``zero`` throws [Error: Invalid key `zero` for argument `NUM`. Valid plural keys for this locale are `one`, `other`, and explicit keys like `=0`](messageformat/messageformat.js/blob/master/lib/index.js#L278)

**Comment by SlexAxton** [comment]
Yea, that sounds like `en-US` (and a bunch of other locales). Not every key is valid for every locale, it is entirely based on the cldr plural forms. For en-US, it's

`if n = 1; ONE; else OTHER`

So using `few` is invalid because it is a dead code branch. But in Slovenian, it'd be perfectly valid.

**Comment by SlexAxton** [comment]
It's also totally valid in an en-US ordinal

**Comment by Spown** [comment]
well, as I said I'm not really familiar with the module, and I don't really know what you are talking about. My point is: if there are some special cases and previously working api/syntax/magic words/whatever, instead of throwing exceptions and declaring the aforementioned mechanics (that is already in cosmumtion out there) as "dead code" you probably should make it backwards compatible.

**Comment by SlexAxton** [comment]
I assume this is one of many reasons that we bumped to a major version. If
you're using those keywords in your en-US messages, they are not valid. I'm
ok throwing an error there.

**Comment by mattgrande** [comment]
Hey @SlexAxton - I assume I should use this page when deciding which keys are supported for which language? http://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html

eg, English is `one` and `other`, while Czech is `one`, `few`, `many`, and `other`?

**Comment by SlexAxton** [comment]
yep. For a tool in the past I’ve dug into internals and just looped through
1000 numbers to see all the keys that pop out, but it’s probably easier to
consume cldr-json these days if you need to know across many langs
programmatically.

**Comment by eemeli** [comment]
Here are the actual categorisation functions used by messageformat, which are of course derived from the CLDR data: https://github.com/eemeli/make-plural/blob/v4.1.1/umd/plurals.js
