### ISSUE TITLE
Let's drop node 0.10 support and expect the Intl object to exist

### ISSUE THREAD

**Issue by eemeli** [messageformat/messageformat.js#173]
As the title states, I think we should start assuming that `Intl` is available. Node 0.10 [usage is now at 6%](https://docs.google.com/spreadsheets/d/1J6TxXIfGOqV9cx1qEFGSXHCma4JHfKPzlsMWfbGmDbE/edit?usp=sharing) (data from npm internals AFAIK) and the last major-ish browser version without it is IE 10. To be clear, `Intl` polyfills are available for both, but I don't think we need to make life more difficult for most users of the library by [defaulting to backwards-compatibility](https://messageformat.github.io/guide/#intl-formatters) as we do currently.

This change would probably mean needing to increment the major version, so it's a good time to also consider other breaking changes, such as my suggested fix for #165, and any changes required to fix #171.

Any thoughts on this?

**Comment by maxkoryukov** [comment]
Probably, this will lead us to better library, so I vote for this changes;)

**Comment by SlexAxton** [comment]
Thanks for the bump. 0.10 doesn't get security updates anymore. #165 isn't super important to me, but I'm fine with it going in. #171 seems more important (even though it's a bit silly in js, it's good for compat). I've always secretly known about it.

**Comment by oliamb** [comment]
I have a different use case, that is an argument in favor of keeping the flag.

I am generating the JS to be read by the browser. I know I can polyfill the `Intl` library but it is really useful to have the option to keep the bundle light by not doing it and using only a subset of ICU string formats.

**Comment by eemeli** [comment]
@oliamb Is it IE10 or some other browser that you're targeting that's the issue? And to be clear, if you're not using any of the formatters that do require `Intl`, this would change nothing in your use case.

**Comment by oliamb** [comment]
Exactly :)

Reading the source, I agree that it won't changes anything as long as I don't generate 'function' tokens. That said, I liked the fact that it was checked at compile time rather than at runtime.

What about having the option enabled by default? I have not the impression that it had a lot of complexity to the code so the feature can be kept. I agree that the default value is not ideal because most users will first face the error before enabling the flag.

And I would like to say thank you for this wonderful library. Simple and so useful!

**Comment by eemeli** [comment]
> What about having the option enabled by default?

That's actually what this issue is all about. But as it's a potentially breaking change, it'll mean needing to increase the major version number.

**Comment by oliamb** [comment]
Right, you convinced me.

That said, the library seems pretty stable so it can be the right time to make a major release. The 1.x will probably not require any maintenance and your user will happily migrate to a new version where the only change is a switch in the command line.

**Comment by eemeli** [comment]
So it looks like we might want to drop node 0.12 support as well, at least from the Travis CI tests. Our API docs are being built by jsdoc, which needed to get updated to work with node 8.5 because of jsdoc3/jsdoc#1438, but on the other hand that's now depending on babel 7.0, which dropped support for node 0.12 with babel/babel#4315.
