### ISSUE TITLE
Handling of apostrophes is incorrect

### ISSUE THREAD

**Issue by nkovacs** [messageformat/messageformat.js#175]
messageformat.js does not handle double apostrophes correctly.

```
var mf = new MessageFormat('en');

console.log(mf.compile("I see '{many}'")());
console.log(mf.compile("I said '{''Wow!''}'")());
console.log(mf.compile("I don't know")());
console.log(mf.compile("I don''t know")());
```

This should output (assuming DOUBLE_OPTIONAL):
1. `I see {many}`
2. `I said {'Wow!'}`
3. `I don't know`
4. `I don't know`

The first two don't work at all, and the fourth one outputs two single quotes instead of one.

See http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessagePattern.ApostropheMode.html

**Comment by maxkoryukov** [comment]
Link to non-Java document: http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping

> If syntax characters occur in the text portions, then they need to be quoted by enclosing the syntax in pairs of ASCII apostrophes. A pair of ASCII apostrophes always represents one ASCII apostrophe, similar to %% in printf representing one %, although this rule still applies inside quoted text. `This '{isn''t}' obvious` → `This {isn't} obvious`

**Comment by nkovacs** [comment]
This is also relevant (from http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessagePattern.ApostropheMode.html#DOUBLE_OPTIONAL)

> A literal apostrophe is represented by either a single or a double apostrophe pattern character. Within a MessageFormat pattern, a single apostrophe only starts quoted literal text if it immediately precedes a curly brace {}, or a pipe symbol | if inside a choice format, or a pound symbol # if inside a plural format.

I've found that a literal apostrophe followed by a `|` or `#` is interpreted as quoted literal text in other cases too, contrary to what the documentation says. E.g. the following php code (which uses the C ICU library):

```php
<?php

$now = time();
var_dump(MessageFormatter::formatMessage("en_US", "This '{' '}' '-' '#' '|' is a test {x,date,y-M-dd '|' '#' hh:mm:ss}", ['x' => $now]));
```

outputs `string(53) "This { } '-' '#' '|' is a test 2017-6-11 | # 06:30:01"`

So the apostrophe only starts a literal text if followed by `{` or `}` outside of `{`, but a `'#'` or `'|'` inside `{` is interpreted as literal text even if it's not choice or plural.

**Comment by nkovacs** [comment]
Since this issue is in the parser, I've opened https://github.com/messageformat/parser/issues/2 instead.
