### ISSUE TITLE
Escaping token IDs

### ISSUE THREAD

**Issue by craigblagg** [messageformat/messageformat.js#179]
Hi,

Is there a generic way to escape token ids when using the select formatter in MessageFormat?

For example given this string:

```
{unit, select, % {percent} em {Em} other {Unknown}}
```

And data such as:

```
{ unit: '%' }
```

An error is thrown - because of the % token in the ICU string.

Lookin through the source, I saw: 

https://github.com/messageformat/messageformat.js/blob/91d7b9baa434c538596bf795f3da61529214d4b2/lib/index.js#L83

Which escapes some characters. But not %. I also tried putting a `\` as `\% {Per...` but still didn’t have any luck.

If there isn’t, and it’s something you would be willing to take a PR on, if you could give some pointers at which point you would expect/prefer something like this (e.g as an enhancement to the `.escape` or in the parser itself), happy to look at putting a PR together.

Many thanks

**Comment by eemeli** [comment]
Unfortunately, that's not possible, as the [standard](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html) requires the select identifiers to match the pattern `[^[[:Pattern_Syntax:][:Pattern_White_Space:]]]+`, and the `[:Pattern_Syntax:]` class [includes](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B%3APattern_Syntax%3A%5D) the `%` sign.

While there are a few places where we do deviate from the standard, this does not really seem like a place where that would be worth doing.
