### ISSUE TITLE
messageformat requires unsafe-eval in Content-Security-Policy

### ISSUE THREAD

**Issue by koosg** [messageformat/messageformat.js#180]
When using a CSP which does not allow unsafe-eval, the 'new Function' throws an EvalError, as per the spec.
However, messageformat uses this:
  if (typeof messages != 'object') {
    var fn = new Function(
        'number, plural, select, fmt', Compiler.funcname(locale),
        'return ' + obj);
    var rt = this.runtime;
    return fn(rt.number, rt.plural, rt.select, this.fmt, pf[locale]);
  }

Is there another way to fix this.

**Comment by SlexAxton** [comment]
If you build your messages (say, as part of your webpack build), they get built into very small, fast functions that don’t violate `unsafe-eval`.

Docs: https://messageformat.github.io/build/

**Comment by Simon-Tesla** [comment]
I have a use case where the message strings are only available at runtime, not build-time, and I cannot change the CSP to allow eval. Is there *any* hope for a mechanism that will allow messageformat to work in that environment?

**Comment by SlexAxton** [comment]
it’s unlikely with our setup I think. The formatjs folks have their own
very similar version though `intl-messageformat` I’m pretty sure. That’ll
do what you’re looking for.
