### ISSUE TITLE
Issue with thai language

### ISSUE THREAD

**Issue by adriengibrat** [messageformat/messageformat.js#186]
Hello, 

I'm using messageformat.js 1.1.0. I have some thai messages that cause `SyntaxError`. 

It seems the character "ว" is the culprit:

```
SyntaxError: Expected [ \t\n\r] or [0-9a-zA-Z$_] but "ว" found.
    at s (messageformat.min.js:formatted:1700)
    at o (messageformat.min.js:formatted:2489)
    at n.compile (messageformat.min.js:formatted:150)
    at o.compile (messageformat.min.js:formatted:310)
```

**Comment by eemeli** [comment]
Could you provide a more complete example of the source string that's causing this error? It looks like you're trying to use an identifier that starts with ว, which is not supported.

**Comment by adriengibrat** [comment]
You're right translations got messed up, I got a property name translated.
