### ISSUE TITLE
Agile Translation workflows and MessageFormat

### ISSUE THREAD

**Issue by jamesbreen5** [messageformat/messageformat.js#187]
Hey, 
I have hit an issue with using MessageFormat as part of a regular translation workflow, and I am looking for some advice - I am assuming my situation is not unique here.
Essentially, what the translation workflow does is inject English strings where no translation exists yet.
This causes all Asian languages to throw up errors with MessageFormat.compile, as they now contain the English one{..} category.
Is there anyway to ignore these errors, as the project essentially stops building until the translations come back in for the Asian languages and replace the English fallback.

**Comment by SlexAxton** [comment]
If you handling doing the fallback, you’ll want to render fallback strings
in the english locale, not the one with missing strings.

It’s been a while though, do we do this fallback somewhere on your behalf?

**Comment by eemeli** [comment]
We don't (yet...) provide fallback between locales, as the compiler output does not include an accessor method. Writing one is relatively simple, though; here's a sketch of something that might be appropriate here (note: haven't tested this specific code at all):

```js
// presuming that you're using messageformat/loader or precompiling your strings
import en from 'messages/en'
import ja from 'messages/ja'

const data = { en, ja }

class Messages {
  availableLocales = Object.keys(data)
  defaultLocale = 'en'
  locale = 'ja'
  has(key, lc) {
    const d = data[lc || this.locale]
    return d && typeof d[key] === 'function'
  }
  get(key, props) {
    if (this.has(key)) {
      return data[this.locale][key](props)
    } else if (this.locale !== this.defaultLocale && this.has(key, this.defaultLocale)) {
      return data[this.defaultLocale][key](props)
    } else {
      return key
    }
  }
}

export default new Messages
```

**Comment by jamesbreen5** [comment]
Thanks, I can handle it on my end so, in how we fall back
