### ISSUE TITLE
Proposal: Split CLI from the core package

### ISSUE THREAD

**Issue by eemeli** [messageformat/messageformat.js#188]
Really the `bin/messageformat.js` CLI is rather separate from the core MessageFormat compiler, so it should probably be separate from it, no? At the same time we could/should rename the main repo as e.g. `messageformat/core` to underline the fact that what it provides is a powerful tool, but that it could/should be used with some sort of wrapper, such as the CLI app or one of the Webpack loaders.

Alternatively, something like a monorepo structure could be considered here, but it would probably not be worth the hassle as most changes are pretty well limited in their scope.

**Comment by SlexAxton** [comment]
👍 as long as we don’t unnecessarily break any current workflows.

**Comment by eemeli** [comment]
The only thing that would break here is that the `messageformat` package would not include the executable; for that you'd need e.g. `messageformat-cli` as well. Still, enough of a change that it warrants the 2.0 label.

**Comment by eemeli** [comment]
[`messageformat-cli`](https://www.npmjs.com/package/messageformat-cli) is now available. To test and use, it should be installed along with the `2.0.0-beta.1` or later version of `messageformat`, which is available under its `next` tag:
```
npm install messageformat@next messageformat-cli
```
